# Generated by Django 4.1.1 on 2022-10-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
