# Generated by Django 4.1.1 on 2022-10-04 23:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=256)),
                ('event_date', models.CharField(max_length=128)),
                ('event_time', models.CharField(max_length=128)),
                ('event_location', models.CharField(max_length=128)),
                ('event_url', models.URLField(max_length=256)),
                ('event_description', models.TextField(max_length=10000)),
            ],
        ),
    ]
