# Generated by Django 4.1.1 on 2022-10-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
