# Generated by Django 4.1.1 on 2022-10-05 03:21

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=None, max_length=128, validators=[events.models.validate_date]),
        ),
    ]
