# Generated by Django 4.1.1 on 2022-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_answered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='date_asked',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
