# Generated by Django 4.1.1 on 2022-10-15 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('donation_name', models.CharField(max_length=256)),
                ('donation_desc', models.TextField(max_length=5000)),
                ('amounted_needed', models.IntegerField()),
            ],
        ),
    ]
