# Generated by Django 4.1.1 on 2022-10-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='amounted_needed',
            new_name='amount_needed',
        ),
    ]
