# Generated by Django 4.1.1 on 2022-10-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donation_amount_raised_donated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount_raised',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
