# Generated by Django 4.1.1 on 2022-10-19 07:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0005_alter_donation_amount_raised'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donated',
            new_name='Donate',
        ),
    ]
